### ISSUE TITLE
Interface is old

### ISSUE THREAD

**Issue by YamiYukiSenpai** [gocarlos/krop#17]
I know it's based on Qt 4, so is there a way to use Oxygen theme instead of some old-fashioned theme from the late 90s?

**Comment by gocarlos** [comment]
cold you retest the latest release?

**Comment by YamiYukiSenpai** [comment]
Sure!  Everything seems to be working well and looks much nicer now.

**Comment by gocarlos** [comment]
Great, then lets close this issue

**Comment by gocarlos** [comment]
👍

**Comment by gocarlos** [comment]
Seems like i cannot close this issue (get error msgs) 😂

**Comment by YamiYukiSenpai** [comment]
Done :-)
