### ISSUE TITLE
is it possible to crop but keep the table of content?

### ISSUE THREAD

**Issue by kupiqu** [gocarlos/krop#21]

**Comment by gocarlos** [comment]
sure, you can set, which pages you want to crop

**Comment by kupiqu** [comment]
What I meant is the following: some pdfs have a listed structure of chapters, sections, etc which are also links to move to those places.

When I crop pdfs, all this information is lost, and I wondered whether it would be possible to maintain it.

**Comment by gocarlos** [comment]
please post this issue upstream: github.com/arminstraub/krop

we only do snap packaging here...
