### ISSUE TITLE
Update Snap release process

### ISSUE THREAD

**Issue by edumco** [gocarlos/krop#26]
The automatic build and release snapcraft is beeing updated and will require some configuration changes

https://snapcraft.io/blog/we-are-changing-the-way-you-build-snaps-from-github-repos

I wonder what is need to be tested before release and how to create these tests

**Comment by gocarlos** [comment]
this repository was already set up according to the intructions that you show in this blog post... 

each commit to this repo's master branch triggers a build and publishes to the edge channel...
